import { NextRequest } from "next/server";
import { GET, POST } from "./route";
import { acknowledgePushNotification, takeNextPushNotification, takePendingPushNotifications } from "@/lib/push/server";
jest.mock("@/lib/push/server", () => ({ acknowledgePushNotification: jest.fn(), takeNextPushNotification: jest.fn(), takePendingPushNotifications: jest.fn() }));
const token = "a".repeat(40), id = "10000000-0000-4000-8000-000000000001";
test("empty queues return null with no-store", async () => { (takeNextPushNotification as jest.Mock).mockResolvedValue(null); const r = await GET(new NextRequest(`https://imenu.test/api/push/next?deviceToken=${token}`)); expect(await r.json()).toBeNull(); expect(r.headers.get("Cache-Control")).toBe("no-store"); });
test("batch requests return every queued notification", async () => { (takePendingPushNotifications as jest.Mock).mockResolvedValue([{ id }]); const r = await GET(new NextRequest(`https://imenu.test/api/push/next?batch=1&deviceToken=${token}`)); expect(await r.json()).toEqual({ notifications: [{ id }] }); });
test("retrieval failures are errors instead of generic alerts", async () => { jest.spyOn(console, "error").mockImplementation(() => undefined); (takeNextPushNotification as jest.Mock).mockRejectedValue(new Error("offline")); expect((await GET(new NextRequest(`https://imenu.test/api/push/next?deviceToken=${token}`))).status).toBe(500); jest.restoreAllMocks(); });
test("only valid device and notification pairs are acknowledged", async () => { const r = await POST(new NextRequest("https://imenu.test/api/push/next", { method: "POST", body: JSON.stringify({ deviceToken: token, notificationId: id }) })); expect(r.status).toBe(200); expect(acknowledgePushNotification).toHaveBeenCalledWith(token, id); const invalid = await POST(new NextRequest("https://imenu.test/api/push/next", { method: "POST", body: JSON.stringify({ deviceToken: "short", notificationId: id }) })); expect(invalid.status).toBe(400); expect(acknowledgePushNotification).toHaveBeenCalledTimes(1); });
