"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/database/supabaseClient";
import { useCreationStore } from "@/lib/stores/restaurant-owner/creationStore";
import Button from "@/components/ui/Button";
import Toast from "@/components/ui/Toast";
import Loader from "@/components/ui/Loader";
import StoreVisuals from "@/components/restaurant-owner/loja/StoreVisuals";
import StoreName from "@/components/restaurant-owner/loja/StoreName";
import CardapioTab from "@/components/restaurant-owner/cardapio/tabs/CardapioTab";
import ManageCategoryModal from "@/components/restaurant-owner/cardapio/ManageCategoryModal";
import ItemDetailsModal from "@/components/restaurant-owner/cardapio/ItemDetailsModal";
import { MenuItemType } from "@/components/restaurant-owner/cardapio/MenuItemRow";
import Card from "@/components/ui/Card";
import ScanMenuModal from "@/components/restaurant-owner/ScanMenuImageModal";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faWandMagicSparkles, faCircleInfo, faCopy, faGlobe } from "@fortawesome/free-solid-svg-icons";
import Input from "@/components/ui/Input";
import Dropdown from "@/components/ui/Dropdown";
import Tooltip from "@/components/ui/Tooltip";
import WarningBox from "@/components/ui/WarningBox";
import AllowedPaymentMethods, { DEFAULT_ALLOWED_PAYMENT_METHODS } from "@/components/restaurant-owner/configuracoes/AllowedPaymentMethods";
import CustomDomainModal from "@/components/restaurant-owner/loja/CustomDomainModal";

type Category = { id: string; name: string; position: number };
type PixKeyType = "CPF" | "CNPJ" | "EMAIL" | "PHONE" | "EVP";
const sanitizeSlug = (value: string) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
const formatPhone = (raw: string) => { const digits = raw.replace(/\D/g, "").replace(/^55(?=\d{10,11}$)/, "").slice(0, 11); if (digits.length <= 2) return digits ? `(${digits}` : ""; if (digits.length <= 7) return `(${digits.slice(0,2)}) ${digits.slice(2)}`; return `(${digits.slice(0,2)}) ${digits.slice(2,7)}-${digits.slice(7)}`; };
const inferPixKeyType = (value: string): PixKeyType | null => { const raw=value.trim(); if(!raw)return null; if(/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(raw))return "EVP"; if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(raw))return "EMAIL"; if(/^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/.test(raw))return "CNPJ"; if(/^\d{3}\.\d{3}\.\d{3}-\d{2}$/.test(raw))return "CPF"; if(/^\+55\D*\d{2}\D*\d{8,9}$/.test(raw)||/^\(\d{2}\)\s*\d{4,5}-?\d{4}$/.test(raw))return "PHONE"; const digits=raw.replace(/\D/g,""); if(digits.length===14)return "CNPJ"; if(digits.length===13&&digits.startsWith("55"))return "PHONE"; return null; };

export default function CriarCardapioPage() {
    const router = useRouter(); const { restaurantId, clear } = useCreationStore();
    const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [toast, setToast] = useState<{message:string;type:"success"|"error"}|null>(null);
    const [visuals, setVisuals] = useState<{logo_url:string|null;banner_url:string|null}>({logo_url:null,banner_url:null}); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [whatsapp,setWhatsapp]=useState(""); const [paymentInfo,setPaymentInfo]=useState(""); const [paymentInfoType,setPaymentInfoType]=useState("AUTO"); const [customDomain,setCustomDomain]=useState<string|null>(null); const [customDomainOpen,setCustomDomainOpen]=useState(false); const [methods,setMethods]=useState<string[]>(DEFAULT_ALLOWED_PAYMENT_METHODS);
    const [categories,setCategories]=useState<Category[]>([]); const [items,setItems]=useState<MenuItemType[]>([]); const [catOpen,setCatOpen]=useState(false); const [catEdit,setCatEdit]=useState<{id:string;name:string}|null>(null); const [itemOpen,setItemOpen]=useState(false); const [itemEdit,setItemEdit]=useState<MenuItemType|null>(null); const [aiOpen,setAiOpen]=useState(false); const [responsiblePhone,setResponsiblePhone]=useState(""); const [needsResponsiblePhone,setNeedsResponsiblePhone]=useState(false);
    const needsPixType=Boolean(paymentInfo.trim()&&!paymentInfoType);

    const autoSave = async (fields: Record<string, unknown>) => {
        if (!restaurantId) return null;
        const response = await fetch(`/api/restaurants/${restaurantId}`, { method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify(fields) });
        const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Erro ao salvar."); return payload;
    };
    const savePaymentInfo=async()=>{if(paymentInfoType==="AUTO"&&paymentInfo.trim()){const detectedType=inferPixKeyType(paymentInfo);if(detectedType){setPaymentInfoType(detectedType);await autoSave({payment_info:paymentInfo,payment_info_type:detectedType});return;}setPaymentInfoType("");await autoSave({payment_info:paymentInfo,payment_info_type:null});return;}await autoSave({payment_info:paymentInfo});};
    const load = async () => {
        if (!restaurantId) return router.replace("/restaurante/login");
        try {
            const { data: { user } } = await supabase.auth.getUser();
            setNeedsResponsiblePhone(!String(user?.user_metadata?.phone || "").replace(/\D/g,""));
            const { data: restaurant, error } = await supabase.from("restaurants").select("id,name,url_slug,logo_url,banner_url,allowed_payment_methods,payment_info,payment_info_type,custom_domain,store_whatsapp").eq("id",restaurantId).single(); if(error||!restaurant) throw new Error("Restaurante não encontrado.");
            setName(restaurant.name||""); setSlug(restaurant.url_slug||""); setWhatsapp(formatPhone(restaurant.store_whatsapp||"")); setPaymentInfo(restaurant.payment_info||""); setPaymentInfoType(restaurant.payment_info_type||(restaurant.payment_info&&!inferPixKeyType(restaurant.payment_info)?"":"AUTO")); setCustomDomain(restaurant.custom_domain||null); setMethods(Array.isArray(restaurant.allowed_payment_methods)&&restaurant.allowed_payment_methods.length?restaurant.allowed_payment_methods:DEFAULT_ALLOWED_PAYMENT_METHODS);
            setVisuals({logo_url:restaurant.logo_url?supabase.storage.from("restaurant-logos").getPublicUrl(restaurant.logo_url).data.publicUrl:null,banner_url:restaurant.banner_url?supabase.storage.from("menu-banners").getPublicUrl(restaurant.banner_url).data.publicUrl:null});
            const [{data:cats},{data:rawItems}] = await Promise.all([supabase.from("categories").select("*").eq("restaurant_id",restaurantId).order("position"),supabase.from("items").select("*").eq("restaurant_id",restaurantId).order("position")]); setCategories(cats||[]); setItems((rawItems||[]).map((item:any)=>({...item,image_url:item.image_path?supabase.storage.from("menu-images").getPublicUrl(item.image_path).data.publicUrl:null})));
        } catch(caught){setToast({message:(caught as Error).message,type:"error"});} finally{setLoading(false);}
    };
    useEffect(()=>{void load();},[restaurantId]);
    const saveName = async()=>{if(!name.trim())return;try{const result=await autoSave({name:name.trim()});if(result?.url_slug)setSlug(result.url_slug);}catch(e){setToast({message:(e as Error).message,type:"error"});}};
    const saveSlug=async()=>{const normalized=sanitizeSlug(slug||name);if(normalized.length<3)return setToast({message:"O endereço precisa ter pelo menos 3 caracteres.",type:"error"});try{const result=await autoSave({url_slug:normalized});setSlug(result.url_slug||normalized);}catch(e){setToast({message:(e as Error).message,type:"error"});}};
    const copyMenuLink=async()=>{await navigator.clipboard.writeText(customDomain?`https://${customDomain}`:`https://imenuapp.com.br/${slug||sanitizeSlug(name)||"nome-da-loja"}`);setToast({message:"Link copiado!",type:"success"});};
    const finish=async()=>{if(!name.trim())return setToast({message:"Informe o nome do restaurante.",type:"error"});const responsiblePhoneDigits=responsiblePhone.replace(/\D/g,"");if(needsResponsiblePhone&&responsiblePhoneDigits.length!==11)return setToast({message:"Informe o celular do responsável.",type:"error"});setSaving(true);try{if(needsResponsiblePhone){const {error:phoneError}=await supabase.auth.updateUser({data:{phone:responsiblePhoneDigits}});if(phoneError)throw phoneError;}await saveName();await saveSlug();await autoSave({store_whatsapp:whatsapp.replace(/\D/g,""),payment_info:paymentInfo,payment_info_type:paymentInfoType==="AUTO"||!paymentInfoType?null:paymentInfoType,allowed_payment_methods:methods,first_time:false,creation_step:4});clear();router.replace("/painel");}catch(e){setToast({message:(e as Error).message,type:"error"});setSaving(false);}};
    if(loading)return <main className="flex min-h-[60vh] items-center justify-center"><Loader className="border-t-brand"/></main>;
    if(!restaurantId)return null;

    return <main className="flex min-h-screen flex-col items-center bg-white px-4 pb-32 pt-4 sm:px-6"><div className="mt-4 w-full max-w-4xl"><div className="mb-8"><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-brand">Etapa 4/4</p><h1 className="text-3xl font-bold">Defina sua Loja</h1><p className="mt-1 text-gray-500">Adicione sua marca e seus primeiros produtos.</p></div>
        <Card className="mb-8 overflow-hidden border border-gray-200 px-4 pb-8 shadow-sm"><StoreVisuals restaurantId={restaurantId} logoUrl={visuals.logo_url} bannerUrl={visuals.banner_url} onUpdate={async(type,publicUrl,dbPath)=>{setVisuals(v=>({...v,[type==="logo"?"logo_url":"banner_url"]:publicUrl}));await autoSave({[type==="logo"?"logo_url":"banner_url"]:dbPath});}} onError={(message)=>setToast({message,type:"error"})}/><StoreName value={name} onChange={setName} onBlur={saveName}/>
        <div className="space-y-6"><div className="grid grid-cols-1 gap-6 md:grid-cols-2"><div className="relative z-10 flex min-w-0 flex-col gap-1"><div className="text-xs font-medium 2xl:text-base">Tipo da chave PIX</div><Dropdown options={[{value:"",label:"Definir tipo de chave"},{value:"AUTO",label:"Detectar automaticamente"},{value:"CPF",label:"CPF"},{value:"CNPJ",label:"CNPJ"},{value:"EMAIL",label:"E-mail"},{value:"PHONE",label:"Telefone"},{value:"EVP",label:"Chave aleatória"}]} value={paymentInfoType} onChange={(event)=>{const nextType=event.target.value;if(nextType==="AUTO"&&paymentInfo.trim()){const detectedType=inferPixKeyType(paymentInfo);if(detectedType){setPaymentInfoType(detectedType);void autoSave({payment_info_type:detectedType});}else{setPaymentInfoType("");void autoSave({payment_info_type:null});}return;}setPaymentInfoType(nextType);void autoSave({payment_info_type:nextType==="AUTO"||!nextType?null:nextType});}}/></div><div className="flex min-w-0 flex-col gap-1"><div className={`flex items-center gap-2 text-xs font-medium 2xl:text-base ${needsPixType?"text-red-600":""}`}><span>Chave Pix para Repasse</span><Tooltip text="Repasses são apenas para clientes que pagaram com Pix Online. Repasses diários às 12:00 no PIX cadastrado." size="medium" showOnClick><FontAwesomeIcon icon={faCircleInfo} className="cursor-help text-gray-500"/></Tooltip></div><Input placeholder="Ex: 123456789" value={paymentInfo} onChange={(e)=>setPaymentInfo(e.target.value)} onBlur={()=>void savePaymentInfo()} className={needsPixType?"border-red-400 focus:border-red-500 focus:ring-red-100":""}/>{needsPixType&&<p className="text-xs font-medium text-red-600">Defina o tipo da chave PIX acima.</p>}</div></div><div className="grid grid-cols-1 gap-6 md:grid-cols-[minmax(0,0.75fr)_minmax(0,1.25fr)_auto] md:gap-4"><Input label="WhatsApp da loja" value={whatsapp} onChange={(e)=>setWhatsapp(formatPhone(e.target.value))} onBlur={()=>void autoSave({store_whatsapp:whatsapp.replace(/\D/g,"")})} maxLength={15}/>{customDomain?<Input label="Link do cardápio" value={customDomain} readOnly locked iconPosition="right" icon={<button type="button" onClick={()=>void copyMenuLink()} aria-label="Copiar link do cardápio" title="Copiar link" className="cursor-pointer text-gray-500 hover:text-brand"><FontAwesomeIcon icon={faCopy}/></button>}/>:<Input label="Link do cardápio" value={slug} placeholder={sanitizeSlug(name)||"nome-da-loja"} onChange={(e)=>setSlug(sanitizeSlug(e.target.value))} onBlur={saveSlug}/>}<Button type="button" variant={customDomain?"secondary":"primary"} onClick={()=>setCustomDomainOpen(true)} className="w-fit shrink-0 self-start border border-transparent py-3! md:mt-5 2xl:mt-8 2xl:text-lg"><FontAwesomeIcon icon={faGlobe} className="mr-2"/>{customDomain?"Domínio conectado":"Usar meu domínio"}</Button></div></div>
        <WarningBox icon={faCircleInfo} className="mt-6 bg-brand! text-white!"><b>AVISO:</b> Repasses de pagamentos em Pix (ONLINE) são realizados diariamente às 12:00 na chave cadastrada.</WarningBox></Card>
        <AllowedPaymentMethods value={methods} onChange={(next)=>{setMethods(next);void autoSave({allowed_payment_methods:next});}} className="mb-8"/>
        <div className="mb-4 flex flex-col justify-between gap-3 px-2 sm:flex-row sm:items-center"><h2 className="text-xl font-bold">Cardápio</h2><button onClick={()=>setAiOpen(true)} className="flex items-center justify-center gap-2 rounded-full bg-gradient-to-br from-[#905CFF] to-[#6A3AFF] px-6 py-3 font-medium text-white"><FontAwesomeIcon icon={faWandMagicSparkles}/>Scanear Cardápio com IA</button></div><div className="rounded-xl border border-gray-100 bg-gray-50/50 p-4"><CardapioTab categories={categories} items={items} restaurantId={restaurantId} onRefresh={load} onItemUpdated={(updatedItem)=>setItems((current)=>current.map((item)=>item.id===updatedItem.id?{...item,...updatedItem}:item))} onEditCategory={(c)=>{setCatEdit(c);setCatOpen(true);}} onOpenItemDetails={(item)=>{setItemEdit(item);setItemOpen(true);}} onNewCategory={()=>{setCatEdit(null);setCatOpen(true);}} onAIScanMenu={setAiOpen}/></div>{needsResponsiblePhone&&<div className="mt-8"><Input label="Celular do Responsável*" type="tel" autoComplete="tel" value={responsiblePhone} maxLength={15} onChange={(e)=>setResponsiblePhone(formatPhone(e.target.value))}/><p className="mt-1 text-xs text-gray-500">Usado para suporte e casos de emergência.</p></div>}</div>
        <div className="fixed inset-x-0 bottom-0 z-40 border-t border-gray-200 bg-white p-4"><div className="mx-auto flex max-w-4xl items-center justify-between"><button onClick={()=>router.back()} className="cursor-pointer font-medium text-brand">Voltar</button><Tooltip text={!name.trim() ? "Você precisa completar os dados primeiro" : ""}><Button onClick={finish} loading={saving} className={`px-8 ${!name.trim()?"!bg-brand/55 hover:!bg-brand/55":""}`}>Salvar e Continuar</Button></Tooltip></div></div>
        <ManageCategoryModal isOpen={catOpen} onClose={()=>setCatOpen(false)} onSuccess={load} restaurantId={restaurantId} categoryToEdit={catEdit}/><ItemDetailsModal isOpen={itemOpen} onClose={()=>setItemOpen(false)} item={itemEdit} restaurantId={restaurantId}/><ScanMenuModal open={aiOpen} onClose={()=>setAiOpen(false)} restaurantId={restaurantId} existingCategories={categories} onRefresh={load}/><CustomDomainModal open={customDomainOpen} onClose={()=>setCustomDomainOpen(false)} restaurantId={restaurantId} initialDomain={customDomain} onDomainChange={setCustomDomain}/>{toast&&<Toast message={toast.message} type={toast.type} onClose={()=>setToast(null)}/>}</main>;
}
